In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\asus\anaconda3\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\asus\anaconda3\lib\site-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [4]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

In [6]:
breast_cancer_wisconsin_diagnostic

{'data': {'ids':            ID
  0      842302
  1      842517
  2    84300903
  3    84348301
  4    84358402
  ..        ...
  564    926424
  565    926682
  566    926954
  567    927241
  568     92751

  [569 rows x 1 columns],
  'features':      radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
  0      17.99     10.38      122.80  1001.0      0.11840       0.27760
  1      20.57     17.77      132.90  1326.0      0.08474       0.07864
  2      19.69     21.25      130.00  1203.0      0.10960       0.15990
  3      11.42     20.38       77.58   386.1      0.14250       0.28390
  4      20.29     14.34      135.10  1297.0      0.10030       0.13280
  ..       ...       ...         ...     ...          ...           ...
  564    21.56     22.39      142.00  1479.0      0.11100       0.11590
  565    20.13     28.25      131.20  1261.0      0.09780       0.10340
  566    16.60     28.08      108.30   858.1      0.08455       0.10230
  567    20.60     29.33      140.10  1265.0      0.11780       0.27700
  568     7.76     24.54       47.92   181.0      0.05263       0.04362

       concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
  0       0.30010          0.14710     0.2419             0.07871  ...   25.380
  1       0.08690          0.07017     0.1812             0.05667  ...   24.990
  2       0.19740          0.12790     0.2069             0.05999  ...   23.570
  3       0.24140          0.10520     0.2597             0.09744  ...   14.910
  4       0.19800          0.10430     0.1809             0.05883  ...   22.540
  ..          ...              ...        ...                 ...  ...      ...
  564     0.24390          0.13890     0.1726             0.05623  ...   25.450
  565     0.14400          0.09791     0.1752             0.05533  ...   23.690
  566     0.09251          0.05302     0.1590             0.05648  ...   18.980
  567     0.35140          0.15200     0.2397             0.07016  ...   25.740
  568     0.00000          0.00000     0.1587             0.05884  ...    9.456

       texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
  0       17.33      184.60  2019.0      0.16220       0.66560      0.7119
  1       23.41      158.80  1956.0      0.12380       0.18660      0.2416
  2       25.53      152.50  1709.0      0.14440       0.42450      0.4504
  3       26.50       98.87   567.7      0.20980       0.86630      0.6869
  4       16.67      152.20  1575.0      0.13740       0.20500      0.4000
  ..        ...         ...     ...          ...           ...         ...
  564     26.40      166.10  2027.0      0.14100       0.21130      0.4107
  565     38.25      155.00  1731.0      0.11660       0.19220      0.3215
  566     34.12      126.70  1124.0      0.11390       0.30940      0.3403
  567     39.42      184.60  1821.0      0.16500       0.86810      0.9387
  568     30.37       59.16   268.6      0.08996       0.06444      0.0000

       concave_points3  symmetry3  fractal_dimension3
  0             0.2654     0.4601             0.11890
  1             0.1860     0.2750             0.08902
  2             0.2430     0.3613             0.08758
  3             0.2575     0.6638             0.17300
  4             0.1625     0.2364             0.07678
  ..               ...        ...                 ...
  564           0.2216     0.2060             0.07115
  565           0.1628     0.2572             0.06637
  566           0.1418     0.2218             0.07820
  567           0.2650     0.4087             0.12400
  568           0.0000     0.2871             0.07039

  [569 rows x 30 columns],
  'targets':     Diagnosis
  0           M
  1           M
  2           M
  3           M
  4           M
  ..        ...
  564         M
  565         M
  566         M
  567         M
  568         B

  [569 rows x 1 columns],
  'original':            ID  radius1  texture1  perimeter1   area1  smoothness1  \
  0      842302    17.99     10.38      122.80  1001.0      0.11840
  1      842517    20.57     17.77      132.90  1326.0      0.08474
  2    84300903    19.69     21.25      130.00  1203.0      0.10960
  3    84348301    11.42     20.38       77.58   386.1      0.14250
  4    84358402    20.29     14.34      135.10  1297.0      0.10030
  ..        ...      ...       ...         ...     ...          ...
  564    926424    21.56     22.39      142.00  1479.0      0.11100
  565    926682    20.13     28.25      131.20  1261.0      0.09780
  566    926954    16.60     28.08      108.30   858.1      0.08455
  567    927241    20.60     29.33      140.10  1265.0      0.11780
  568     92751     7.76     24.54       47.92   181.0      0.05263

       compactness1  concavity1  concave_points1  symmetry1  ...  texture3  \
  0         0.27760     0.30010          0.14710     0.2419  ...     17.33
  1         0.07864     0.08690          0.07017     0.1812  ...     23.41
  2         0.15990     0.19740          0.12790     0.2069  ...     25.53
  3         0.28390     0.24140          0.10520     0.2597  ...     26.50
  4         0.13280     0.19800          0.10430     0.1809  ...     16.67
  ..            ...         ...              ...        ...  ...       ...
  564       0.11590     0.24390          0.13890     0.1726  ...     26.40
  565       0.10340     0.14400          0.09791     0.1752  ...     38.25
  566       0.10230     0.09251          0.05302     0.1590  ...     34.12
  567       0.27700     0.35140          0.15200     0.2397  ...     39.42
  568       0.04362     0.00000          0.00000     0.1587  ...     30.37

       perimeter3   area3  smoothness3  compactness3  concavity3  \
  0        184.60  2019.0      0.16220       0.66560      0.7119
  1        158.80  1956.0      0.12380       0.18660      0.2416
  2        152.50  1709.0      0.14440       0.42450      0.4504
  3         98.87   567.7      0.20980       0.86630      0.6869
  4        152.20  1575.0      0.13740       0.20500      0.4000
  ..          ...     ...          ...           ...         ...
  564      166.10  2027.0      0.14100       0.21130      0.4107
  565      155.00  1731.0      0.11660       0.19220      0.3215
  566      126.70  1124.0      0.11390       0.30940      0.3403
  567      184.60  1821.0      0.16500       0.86810      0.9387
  568       59.16   268.6      0.08996       0.06444      0.0000

       concave_points3  symmetry3  fractal_dimension3  Diagnosis
  0             0.2654     0.4601             0.11890          M
  1             0.1860     0.2750             0.08902          M
  2             0.2430     0.3613             0.08758          M
  3             0.2575     0.6638             0.17300          M
  4             0.1625     0.2364             0.07678          M
  ..               ...        ...                 ...        ...
  564           0.2216     0.2060             0.07115          M
  565           0.1628     0.2572             0.06637          M
  566           0.1418     0.2218             0.07820          M
  567           0.2650     0.4087             0.12400          M
  568           0.0000     0.2871             0.07039          B

  [569 rows x 32 columns],
  'headers': Index(['ID', 'radius1', 'texture1', 'perimeter1', 'area1', 'smoothness1',
         'compactness1', 'concavity1', 'concave_points1', 'symmetry1',
         'fractal_dimension1', 'radius2', 'texture2', 'perimeter2', 'area2',
         'smoothness2', 'compactness2', 'concavity2', 'concave_points2',
         'symmetry2', 'fractal_dimension2', 'radius3', 'texture3', 'perimeter3',
         'area3', 'smoothness3', 'compactness3', 'concavity3', 'concave_points3',
         'symmetry3', 'fractal_dimension3', 'Diagnosis'],
        dtype='object')},
 'metadata': {'uci_id': 17,
  'name': 'Breast Cancer Wisconsin (Diagnostic)',
  'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic',
  'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv',
  'abstract': 'Diagnostic Wisconsin Breast Cancer Database.',
  'area': 'Health and Medicine',
  'tasks': ['Classification'],
  'characteristics': ['Multivariate'],
  'num_instances': 569,
  'num_features': 30,
  'feature_types': ['Real'],
  'demographics': [],
  'target_col': ['Diagnosis'],
  'index_col': ['ID'],
  'has_missing_values': 'no',
  'missing_values_symbol': None,
  'year_of_dataset_creation': 1993,
  'last_updated': 'Fri Nov 03 2023',
  'dataset_doi': '10.24432/C5DW2B',
  'creators': ['William Wolberg',
   'Olvi Mangasarian',
   'Nick Street',
   'W. Street'],
  'intro_paper': {'ID': 230,
   'type': 'NATIVE',
   'title': 'Nuclear feature extraction for breast tumor diagnosis',
   'authors': 'W. Street, W. Wolberg, O. Mangasarian',
   'venue': 'Electronic imaging',
   'year': 1993,
   'journal': None,
   'DOI': '10.1117/12.148698',
   'URL': 'https://www.semanticscholar.org/paper/53f0fbb425bc14468eb3bf96b2e1d41ba8087f36',
   'sha': None,
   'corpus': None,
   'arxiv': None,
   'mag': None,
   'acl': None,
   'pmid': None,
   'pmcid': None},
  'additional_info': {'summary': 'Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass.  They describe characteristics of the cell nuclei present in the image. A few of the images can be found at http://www.cs.wisc.edu/~street/images/\r\n\r\nSeparating plane described above was obtained using Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree Construction Via Linear Programming." Proceedings of the 4th Midwest Artificial Intelligence and Cognitive Science Society, pp. 97-101, 1992], a classification method which uses linear programming to construct a decision tree.  Relevant features were selected using an exhaustive search in the space of 1-4 features and 1-3 separating planes.\r\n\r\nThe actual linear program used to obtain the separating plane in the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].\r\n\r\nThis database is also available through the UW CS ftp server:\r\nftp ftp.cs.wisc.edu\r\ncd math-prog/cpo-dataset/machine-learn/WDBC/',
   'purpose': None,
   'funded_by': None,
   'instances_represent': None,
   'recommended_data_splits': None,
   'sensitive_data': None,
   'preprocessing_description': None,
   'variable_info': '1) ID number\r\n2) Diagnosis (M = malignant, B = benign)\r\n3-32)\r\n\r\nTen real-valued features are computed for each cell nucleus:\r\n\r\n\ta) radius (mean of distances from center to points on the perimeter)\r\n\tb) texture (standard deviation of gray-scale values)\r\n\tc) perimeter\r\n\td) area\r\n\te) smoothness (local variation in radius lengths)\r\n\tf) compactness (perimeter^2 / area - 1.0)\r\n\tg) concavity (severity of concave portions of the contour)\r\n\th) concave points (number of concave portions of the contour)\r\n\ti) symmetry \r\n\tj) fractal dimension ("coastline approximation" - 1)',
   'citation': None}},
 'variables':                   name     role         type demographic description units  \
 0                   ID       ID  Categorical        None        None  None
 1            Diagnosis   Target  Categorical        None        None  None
 2              radius1  Feature   Continuous        None        None  None
 3             texture1  Feature   Continuous        None        None  None
 4           perimeter1  Feature   Continuous        None        None  None
 5                area1  Feature   Continuous        None        None  None
 6          smoothness1  Feature   Continuous        None        None  None
 7         compactness1  Feature   Continuous        None        None  None
 8           concavity1  Feature   Continuous        None        None  None
 9      concave_points1  Feature   Continuous        None        None  None
 10           symmetry1  Feature   Continuous        None        None  None
 11  fractal_dimension1  Feature   Continuous        None        None  None
 12             radius2  Feature   Continuous        None        None  None
 13            texture2  Feature   Continuous        None        None  None
 14          perimeter2  Feature   Continuous        None        None  None
 15               area2  Feature   Continuous        None        None  None
 16         smoothness2  Feature   Continuous        None        None  None
 17        compactness2  Feature   Continuous        None        None  None
 18          concavity2  Feature   Continuous        None        None  None
 19     concave_points2  Feature   Continuous        None        None  None
 20           symmetry2  Feature   Continuous        None        None  None
 21  fractal_dimension2  Feature   Continuous        None        None  None
 22             radius3  Feature   Continuous        None        None  None
 23            texture3  Feature   Continuous        None        None  None
 24          perimeter3  Feature   Continuous        None        None  None
 25               area3  Feature   Continuous        None        None  None
 26         smoothness3  Feature   Continuous        None        None  None
 27        compactness3  Feature   Continuous        None        None  None
 28          concavity3  Feature   Continuous        None        None  None
 29     concave_points3  Feature   Continuous        None        None  None
 30           symmetry3  Feature   Continuous        None        None  None
 31  fractal_dimension3  Feature   Continuous        None        None  None

    missing_values
 0              no
 1              no
 2              no
 3              no
 4              no
 5              no
 6              no
 7              no
 8              no
 9              no
 10             no
 11             no
 12             no
 13             no
 14             no
 15             no
 16             no
 17             no
 18             no
 19             no
 20             no
 21             no
 22             no
 23             no
 24             no
 25             no
 26             no
 27             no
 28             no
 29             no
 30             no
 31             no  }

In [7]:
# data (as pandas dataframes)
X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets

In [8]:
X.shape

(569, 30)

In [9]:
X.columns.to_list()

['radius1',
 'texture1',
 'perimeter1',
 'area1',
 'smoothness1',
 'compactness1',
 'concavity1',
 'concave_points1',
 'symmetry1',
 'fractal_dimension1',
 'radius2',
 'texture2',
 'perimeter2',
 'area2',
 'smoothness2',
 'compactness2',
 'concavity2',
 'concave_points2',
 'symmetry2',
 'fractal_dimension2',
 'radius3',
 'texture3',
 'perimeter3',
 'area3',
 'smoothness3',
 'compactness3',
 'concavity3',
 'concave_points3',
 'symmetry3',
 'fractal_dimension3']

In [11]:
X = X.drop(X[['perimeter1',
 'area1',
 'smoothness1',
 'compactness1',
 'concavity1',
 'concave_points1',
 'symmetry1',
 'fractal_dimension1',
 'radius2',
 'texture2',
 'area2',
 'smoothness2',
 'compactness2',
 'concavity2',
 'concave_points2',
 'symmetry2',
 'fractal_dimension2',
 'radius3',
 'texture3',
 'perimeter3',
 'area3',
 'smoothness3',
 'compactness3',
 'concavity3',
 'concave_points3',
 'symmetry3',
 'fractal_dimension3']],axis=1)

In [12]:
X

     radius1  texture1  perimeter2
0      17.99     10.38       8.589
1      20.57     17.77       3.398
2      19.69     21.25       4.585
3      11.42     20.38       3.445
4      20.29     14.34       5.438
..       ...       ...         ...
564    21.56     22.39       7.673
565    20.13     28.25       5.203
566    16.60     28.08       3.425
567    20.60     29.33       5.772
568     7.76     24.54       2.548

[569 rows x 3 columns]

In [13]:
y

    Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [14]:
import warnings
warnings.filterwarnings('ignore')

In [15]:
y['Diagnosis'] = y['Diagnosis'].map({'M': 1, 'B': 0})

In [16]:
y

     Diagnosis
0            1
1            1
2            1
3            1
4            1
..         ...
564          1
565          1
566          1
567          1
568          0

[569 rows x 1 columns]

In [17]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

In [18]:
clf.fit(X, y)

SVC(kernel='linear')